"""Official/public contacts for the frozen PLUMBING_CORE Top 25.

Sourced from official company websites unless noted. Inferred emails stay
INFERRED_UNVERIFIED. Does not change ranking scores.
"""

from __future__ import annotations

from pipeline.contactability.normalize import CANDIDATE, VERIFIED

def _ch(ctype, value, *, ref, status=VERIFIED, family="official_website", conf=95.0, **extra):
    rec = {
        "contact_type": ctype,
        "contact_value": value,
        "verification_status": status,
        "source_family": family,
        "source_reference": ref,
        "confidence": conf,
    }
    rec.update(extra)
    return rec


# compact_company_name(display_name) -> channels
OFFICIAL_PLUMBING_CORE = {
    "PARKER AND SONS": [
        _ch("website", "https://www.parkerandsons.com/", ref="https://www.parkerandsons.com/"),
        _ch("business_phone", "(602) 344-9027", ref="https://www.parkerandsons.com/"),
        _ch("contact_form", "https://www.parkerandsons.com/", ref="https://www.parkerandsons.com/", conf=90.0,
            notes="Official homepage publishes the live business line; no public estimating inbox found."),
        _ch("named_contact", "Daryl Bingham", ref="https://www.parkerandsons.com/",
            contact_name="Daryl Bingham", title="President", conf=85.0, family="prior_research",
            notes="President already on file from prior research; official site confirms the business line."),
    ],
    "SIGNATURE PLUMBING AZ": [
        _ch("website", "https://signature-az.com/", ref="https://signature-az.com/", conf=92.0,
            notes="Official domain publishes ROC# 353753 matching the verified license."),
        _ch("business_phone", "(480) 862-5549", ref="https://signature-az.com/"),
        _ch("business_email", "signatureplumbingaz@gmail.com", ref="https://signature-az.com/", conf=88.0,
            notes="Published on the official site as the service inbox."),
        _ch("named_contact", "Garth A Knight", ref="https://opengovus.com/arizona-corporation/L19272334",
            status=CANDIDATE, family="public_business_record", conf=70.0,
            contact_name="Garth A Knight", title="Member",
            notes="Arizona Corporation Commission member listing. Not an official website staff page."),
    ],
    "DESERT WATER PLUMBING": [
        _ch("website", "https://www.desertwateraz.com/", ref="https://www.desertwateraz.com/"),
        _ch("business_phone", "602-699-4401", ref="https://www.desertwateraz.com/contact-us/"),
        _ch("contact_form", "https://www.desertwateraz.com/contact-us/", ref="https://www.desertwateraz.com/contact-us/", conf=90.0),
        _ch("business_address", "8301 W Foothill Dr, Peoria, AZ 85383", ref="https://www.desertwateraz.com/contact-us/", conf=92.0),
    ],
    "FELIX PLUMBING AND ROOTER": [
        _ch("website", "https://felixplumbingaz.com/", ref="https://felixplumbingaz.com/",
            status=CANDIDATE, family="public_directory", conf=60.0,
            notes="Official-looking domain listed on BBB. Live fetch was bot-walled; not independently re-read."),
        _ch("business_phone", "(602) 535-6172", ref="https://www.bbb.org/us/az/mesa/profile/plumber/felix-plumbing-rooter-llc-1126-1000002238",
            status=CANDIDATE, family="bbb", conf=70.0,
            notes="BBB business listing. Address 332 E Harvard Ave Gilbert matches ROC."),
        _ch("named_contact", "Jesus Diaz Felix", ref="roc_contact_candidates:qualifying_party",
            status=CANDIDATE, family="roc", conf=55.0,
            contact_name="Jesus Diaz Felix", title="Qualifying party",
            notes="ROC qualifying party. Not treated as a verified buyer."),
    ],
    "PATRICK RILEY COOLING HEATING AND PLUMBING": [
        _ch("website", "https://patrickrileyservices.com/", ref="https://patrickrileyservices.com/"),
        _ch("business_phone", "(602) 286-0027", ref="https://patrickrileyservices.com/", conf=95.0,
            notes="Published on the official homepage for same-day service."),
        _ch("office", "(602) 638-2465", ref="https://patrickrileyservices.com/about/contact", conf=90.0,
            notes="Official schema.org telephone on the contact page."),
        _ch("business_email", "internet@patrickrileyac.com", ref="https://patrickrileyservices.com/about/contact", conf=90.0),
        _ch("contact_form", "https://patrickrileyservices.com/about/contact", ref="https://patrickrileyservices.com/about/contact", conf=90.0),
        _ch("business_address", "1850 E. Watkins St., Phoenix, AZ 85034", ref="https://patrickrileyservices.com/", conf=92.0),
    ],
    "TRAVIS AND SONS PLUMBING": [
        _ch("website", "https://www.travisandsonsplumbing.com/", ref="https://www.travisandsonsplumbing.com/"),
        _ch("business_phone", "(480) 837-9422", ref="https://www.travisandsonsplumbing.com/",
            notes="Office line published on the official site."),
        _ch("office", "(480) 933-0208", ref="https://www.travisandsonsplumbing.com/", conf=90.0,
            notes="After-hours / questions line published on the official site."),
        _ch("named_contact", "Cody Howard", ref="https://www.bbb.org/us/az/mesa/profile/plumber/travis-sons-plumbing-rooter-1126-1000105836",
            status=CANDIDATE, family="bbb", conf=70.0,
            contact_name="Cody Howard", title="President/Director"),
        _ch("business_address", "16930 E Palisades Blvd Suite #100-L, Fountain Hills, AZ 85268",
            ref="https://www.travisandsonsplumbing.com/", conf=92.0),
    ],
    "BRISAS PLUMBING": [
        _ch("website", "https://brisasplumbingphoenix.com/", ref="https://brisasplumbingphoenix.com/"),
        _ch("business_phone", "(623) 738-0522", ref="https://brisasplumbingphoenix.com/"),
        _ch("business_email", "daniel@brisasplumbing.com", ref="https://brisasplumbingphoenix.com/", conf=92.0),
        _ch("contact_form", "https://brisasplumbingphoenix.com/", ref="https://brisasplumbingphoenix.com/", conf=88.0),
        _ch("named_contact", "Daniel", ref="https://brisasplumbingphoenix.com/", conf=70.0,
            contact_name="Daniel", title="General contact",
            notes="Email local-part only; original title not published. Classified GENERAL_CONTACT."),
    ],
    "COOLING AND PLUMBING": [
        _ch("website", "https://azcpg.com/", ref="https://azcpg.com/"),
        _ch("business_phone", "(480) 813-1155", ref="https://azcpg.com/"),
        _ch("business_email", "info@azcpg.com", ref="https://azcpg.com/", conf=95.0),
        _ch("business_address", "5026 E Main St UNIT 16, Mesa, AZ 85205", ref="https://azcpg.com/", conf=90.0,
            notes="Street address and PO Box 42064 both published; ROC uses the PO Box."),
    ],
    "THE COOLING AND PLUMBING CO": [
        _ch("website", "https://azcpg.com/", ref="https://azcpg.com/"),
        _ch("business_phone", "(480) 813-1155", ref="https://azcpg.com/"),
        _ch("business_email", "info@azcpg.com", ref="https://azcpg.com/", conf=95.0),
    ],
    "COOLING AND PLUMBING CO": [
        _ch("website", "https://azcpg.com/", ref="https://azcpg.com/"),
        _ch("business_phone", "(480) 813-1155", ref="https://azcpg.com/"),
        _ch("business_email", "info@azcpg.com", ref="https://azcpg.com/", conf=95.0),
    ],
    "CLEAR WAY ROOTER AND PLUMBING": [
        _ch("website", "https://www.clearwayaz.com/", ref="https://www.clearwayaz.com/",
            notes="Official homepage publishes 623-764-8566. Direct fetch returned HTTP 500 this pass."),
        _ch("business_phone", "(623) 764-8566", ref="https://www.clearwayaz.com/"),
        _ch("contact_form", "http://www.clearwayaz.com/index.php/request-quote",
            ref="http://www.clearwayaz.com/index.php/request-quote", conf=88.0),
        _ch("named_contact", "Paul Ruvacalva", ref="https://www.clearwayaz.com/", conf=80.0,
            contact_name="Paul Ruvacalva", title="Owner",
            notes="Official site describes Paul Ruvacalva as the owner/operator."),
    ],
    "TEK STAR PLUMBING AND MECHANICAL": [
        _ch("website", "https://www.tekstarplumbing.com/", ref="https://www.tekstarplumbing.com/"),
        _ch("business_phone", "602-224-3756", ref="https://www.tekstarplumbing.com/contact",
            notes="Service / tenant-improvement line."),
        _ch("office", "602-224-2470", ref="https://www.tekstarplumbing.com/contact", conf=92.0,
            title="New Construction", notes="New-construction line on the official contact page."),
        _ch("business_email", "AZ@TEKSTARPLUMBING.COM", ref="https://www.tekstarplumbing.com/contact", conf=95.0),
        _ch("contact_form", "https://www.tekstarplumbing.com/contact", ref="https://www.tekstarplumbing.com/contact", conf=90.0),
        _ch("named_contact", "Vince Velonis", ref="https://www.tekstarplumbing.com/about",
            contact_name="Vince Velonis", title="President"),
        _ch("named_contact", "Victoria Nogales", ref="https://www.tekstarplumbing.com/about",
            contact_name="Victoria Nogales", title="Office Administrator"),
        _ch("business_address", "3033 N. 20th Street, Phoenix, AZ 85016",
            ref="https://www.tekstarplumbing.com/contact", conf=95.0),
    ],
    "SILVER STATE PLUMBING": [
        _ch("website", "https://silverstate.com/", ref="https://silverstate.com/service-areas/phoenix-az/"),
        _ch("business_phone", "(520) 477-8377", ref="https://silverstate.com/service-areas/phoenix-az/",
            notes="Phoenix service line on the official Arizona location page. HQ is Las Vegas; AZ CR-37 359760."),
        _ch("office", "(725) 213-7309", ref="https://silverstate.com/service-areas/phoenix-az/", conf=85.0,
            notes="24/7 emergency line published on the official site."),
        _ch("business_address", "3416 S 48th St., Suites 10,11 Phoenix, AZ 85040",
            ref="https://silverstate.com/service-areas/phoenix-az/", conf=90.0),
        _ch("contact_form", "https://silverstate.com/service-areas/phoenix-az/",
            ref="https://silverstate.com/service-areas/phoenix-az/", conf=88.0),
    ],
    "LOCAL LEADERS PLUMBING": [
        _ch("website", "https://localleadersplumbing.com/", ref="https://localleadersplumbing.com/"),
        _ch("business_phone", "(480) 822-0808", ref="https://localleadersplumbing.com/contact-us/"),
        _ch("business_email", "info@localleadersplumbing.com", ref="https://localleadersplumbing.com/contact-us/"),
        _ch("named_contact", "Mike", ref="https://localleadersplumbing.com/",
            contact_name="Mike", title="Owner",
            notes="Official homepage: 'Hi, I'm Mike, owner of Local Leaders Plumbing.' ROC match is POSSIBLE (Desert Horizon 304456)."),
        _ch("business_address", "2501 W Behrend Dr Suites F-73, Phoenix AZ 85027",
            ref="https://localleadersplumbing.com/contact-us/", conf=92.0),
    ],
    "SLP ALLIANCE TRADE SERVICES": [
        _ch("website", "https://alliancetrade.com/", ref="https://alliancetrade.com/"),
        _ch("business_phone", "(480) 785-7459", ref="https://alliancetrade.com/",
            notes="Official footer. ROC #350041 / #350042 match the site."),
        _ch("business_email", "contact@alliancetrade.com", ref="https://alliancetrade.com/"),
        _ch("business_address", "2626 E Elwood St, Phoenix, AZ 85040", ref="https://alliancetrade.com/", conf=95.0),
        _ch("estimator", "contact@alliancetrade.com", ref="https://alliancetrade.com/", conf=80.0,
            title="Request a Proposal", notes="Official site CTA is 'Request a Proposal' to this inbox."),
    ],
    "APACHE PLUMBING SERVICES": [
        _ch("website", "https://www.apacheplumbingservices.com/", ref="https://www.apacheplumbingservices.com/"),
        _ch("business_phone", "602-246-2944", ref="https://www.apacheplumbingservices.com/contact"),
        _ch("business_email", "apacheplumbing@cox.net", ref="https://www.apacheplumbingservices.com/contact"),
        _ch("business_address", "6827 N Black Canyon Hwy, Phoenix, AZ 85015",
            ref="https://www.apacheplumbingservices.com/contact", conf=90.0),
        _ch("named_contact", "Frank Steven Davis", ref="roc_contact_candidates:qualifying_party",
            status=CANDIDATE, family="roc", conf=50.0,
            contact_name="Frank Steven Davis", title="Qualifying party",
            notes="ROC QP. Official site publishes ROC #212201 matching Lacy Rain LLC."),
    ],
    "WEST COAST PLUMBING": [
        _ch("website", "https://westcoastplumbingandair.com/", ref="https://westcoastplumbingandair.com/",
            status=CANDIDATE, family="public_directory", conf=55.0,
            notes="Name match only. CorridorIQ identity is UNRESOLVED and permits have no license number. Confirm ROC 221431/274551 before quoting."),
        _ch("business_phone", "(623) 582-1117", ref="https://westcoastplumbingandair.com/contact-us/",
            status=CANDIDATE, family="public_directory", conf=55.0),
        _ch("contact_form", "https://westcoastplumbingandair.com/contact-us/",
            ref="https://westcoastplumbingandair.com/contact-us/",
            status=CANDIDATE, family="public_directory", conf=50.0),
    ],
    "ARIZONA DELTA MECHANICAL": [
        _ch("website", "https://deltamechanical.com/", ref="https://deltamechanical.com/",
            status=CANDIDATE, family="public_directory", conf=65.0,
            notes="Same Mesa Baseline #155 address as Delta Mechanical Inc. Official site was Cloudflare-blocked this pass."),
        _ch("business_phone", "(480) 898-0007",
            ref="https://azroc.my.site.com/AZRoc/s/contractor-search",
            status=CANDIDATE, family="public_licensing", conf=75.0,
            notes="Arizona ROC contractor listing publishes 4808980007 for Delta Mechanical Inc at 6056 E Baseline Rd #155, the same address as Arizona Delta Mechanical Inc licenses 314342/315925."),
        _ch("office", "(866) 898-0007", ref="https://www.allbiz.com/business/delta-plumbing-repipe-and-drains-866-898-0007",
            status=CANDIDATE, family="public_directory", conf=55.0),
    ],
    "AZ DELTA MECHANICAL": [
        _ch("website", "https://deltamechanical.com/", ref="https://deltamechanical.com/",
            status=CANDIDATE, family="public_directory", conf=50.0,
            notes="Permit-name variant of Arizona Delta Mechanical / Delta Mechanical. No independent ROC row."),
        _ch("business_phone", "(480) 898-0007",
            ref="https://azroc.my.site.com/AZRoc/s/contractor-search",
            status=CANDIDATE, family="canonical_peer", conf=60.0,
            notes="Inherited from the Arizona Delta Mechanical / Delta Mechanical Baseline address cluster."),
    ],
    "Z PLUMBING": [
        _ch("business_phone", "(480) 249-6444",
            ref="https://www.bbb.org/us/az/scottsdale/profile/plumber/z-plumbing-llc-1126-1000060257",
            status=CANDIDATE, family="bbb", conf=70.0,
            notes="BBB listing. ROC qualifying party Zaw Rip Sumlut is listed as Owner. No official website found."),
        _ch("named_contact", "Zaw Rip Sumlut",
            ref="https://www.bbb.org/us/az/scottsdale/profile/plumber/z-plumbing-llc-1126-1000060257",
            status=CANDIDATE, family="bbb", conf=70.0,
            contact_name="Zaw Rip Sumlut", title="Owner"),
        _ch("business_address", "4819 N 82nd St, Scottsdale, AZ 85251",
            ref="https://www.bbb.org/us/az/scottsdale/profile/plumber/z-plumbing-llc-1126-1000060257",
            status=CANDIDATE, family="bbb", conf=70.0),
    ],
    "ADVANCED PLUMBING AND PIPING": [
        _ch("website", "https://advancedplumbingandpiping.com/", ref="https://advancedplumbingandpiping.com/"),
        _ch("contact_form", "https://advancedplumbingandpiping.com/", ref="https://advancedplumbingandpiping.com/", conf=88.0,
            notes="Official site invites an online form or a call for a free inspection."),
    ],
    "JMAX MECHANICAL": [
        _ch("website", "https://www.jmaxmechanical.com/", ref="https://www.jmaxmechanical.com/",
            family="prior_research", conf=90.0),
        _ch("business_phone", "(480) 322-1742", ref="https://www.jmaxmechanical.com/",
            family="prior_research"),
        _ch("business_email", "justin@jmaxplumbing.com", ref="https://www.jmaxmechanical.com/",
            family="prior_research", contact_name="Justin Bowie", title="Owner"),
        _ch("named_contact", "Justin Bowie", ref="https://www.jmaxmechanical.com/",
            family="prior_research", contact_name="Justin Bowie", title="Owner"),
    ],
}
