"""Known-company lane explanations for the Phase 4F validation report."""

KNOWN = (
    "Arizona Propane",
    "Canyon State Propane",
    "RP Gas Piping",
    "Millennium Gas",
    "Propane Services",
    "Parker & Sons",
    "Gas Piping Inc",
    "Kerns Plumbing",
    "AmeriGas",
    "Ferrell",
    "RCI Systems",
    "R C I Systems",
    "Metering Services",
    "Metro Fire",
    "ABC Water Works",
    "Creative Environments",
    "United Integrated",
    "Austin Commercial",
    "Petra",
    "Arrowmark",
    "Midwest Contracting",
    "Rider Permit",
    "Kris Espinoza",
    "Stephanie Sekona",
    "ToyotaLift",
)
